### ISSUE TITLE
error: unknown option '--url'

### ISSUE THREAD

**Issue by warpkwd** [alexa/skill-sample-python-sauce-boss#12]
ask new --url https://github.com/alexa/skill-sample-python-sauce-boss.git --skill-name sauce-boss
error: unknown option '--url'

How can I do?

**Comment by gilleswb** [comment]
Following command  " ask new --url <repo> --skill-name <folder>" was deprecated after version 0 and 1 for ask-CLI documented [here](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference-v1.html#new-command) - 
`ask new --url https://github.com/alexa/skill-sample-python-sauce-boss.git --skill-name sauce-boss`

Need to update README according to latest ASK-CLI version

Please follow current(v2) format for ask-CLI skill template cloning documented [here](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#new-command)

Following command works on V2 of ASK-CLI, and allows to follow steps to create skill
`ask new --template-branch https://github.com/alexa-samples/skill-sample-python-sauce-boss.git`

Working on updating this READ-ME accordingly
