### ISSUE TITLE
How to add external modules to the alexa skill code editor

### ISSUE THREAD

**Issue by Saranlisto** [alexa/skill-sample-python-sauce-boss#3]
I am building an alexa skill using Alexa-Hosted lambda in Python. I want to import modules like matlabplot, snowflake-connector-python. How should I do that?

**Comment by warpkwd** [comment]
ask new --url https://github.com/alexa/skill-sample-python-sauce-boss.git --skill-name sauce-boss
error: unknown option '--url'

**Comment by dievaa** [comment]
You can find an answer to your question from the Amazon Developer Forum here:
https://amazon.developer.forums.answerhub.com/questions/235429/how-to-add-custom-import-in-alexa-skill-python.html
